export const LOAD_FEED_SUCCESS = 'LOAD_FEED_SUCCESS';
export const APPEND_FEED_SUCCESS = 'APPEND_FEED_SUCCESS';
export const ADD_TO_SAVED = 'ADD_TO_SAVED';
export const REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVED';